######################################################################
# Automatically generated by qmake (2.00a) Do Feb 14 04:37:14 2008
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += lze.pro
